// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logica.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistroLogistica struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Tipo                 string   `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre               string   `protobuf:"bytes,4,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor                int32    `protobuf:"varint,5,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen               string   `protobuf:"bytes,6,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino              string   `protobuf:"bytes,7,opt,name=destino,proto3" json:"destino,omitempty"`
	Seguimento           int32    `protobuf:"varint,8,opt,name=seguimento,proto3" json:"seguimento,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistroLogistica) Reset()         { *m = RegistroLogistica{} }
func (m *RegistroLogistica) String() string { return proto.CompactTextString(m) }
func (*RegistroLogistica) ProtoMessage()    {}
func (*RegistroLogistica) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa61bfb35dfa745, []int{0}
}

func (m *RegistroLogistica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistroLogistica.Unmarshal(m, b)
}
func (m *RegistroLogistica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistroLogistica.Marshal(b, m, deterministic)
}
func (m *RegistroLogistica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistroLogistica.Merge(m, src)
}
func (m *RegistroLogistica) XXX_Size() int {
	return xxx_messageInfo_RegistroLogistica.Size(m)
}
func (m *RegistroLogistica) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistroLogistica.DiscardUnknown(m)
}

var xxx_messageInfo_RegistroLogistica proto.InternalMessageInfo

func (m *RegistroLogistica) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *RegistroLogistica) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegistroLogistica) GetTipo() string {
	if m != nil {
		return m.Tipo
	}
	return ""
}

func (m *RegistroLogistica) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *RegistroLogistica) GetValor() int32 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *RegistroLogistica) GetOrigen() string {
	if m != nil {
		return m.Origen
	}
	return ""
}

func (m *RegistroLogistica) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *RegistroLogistica) GetSeguimento() int32 {
	if m != nil {
		return m.Seguimento
	}
	return 0
}

type Camion struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Camion) Reset()         { *m = Camion{} }
func (m *Camion) String() string { return proto.CompactTextString(m) }
func (*Camion) ProtoMessage()    {}
func (*Camion) Descriptor() ([]byte, []int) {
	return fileDescriptor_8fa61bfb35dfa745, []int{1}
}

func (m *Camion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Camion.Unmarshal(m, b)
}
func (m *Camion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Camion.Marshal(b, m, deterministic)
}
func (m *Camion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Camion.Merge(m, src)
}
func (m *Camion) XXX_Size() int {
	return xxx_messageInfo_Camion.Size(m)
}
func (m *Camion) XXX_DiscardUnknown() {
	xxx_messageInfo_Camion.DiscardUnknown(m)
}

var xxx_messageInfo_Camion proto.InternalMessageInfo

func (m *Camion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*RegistroLogistica)(nil), "proto.Registro_logistica")
	proto.RegisterType((*Camion)(nil), "proto.Camion")
}

func init() {
	proto.RegisterFile("logica.proto", fileDescriptor_8fa61bfb35dfa745)
}

var fileDescriptor_8fa61bfb35dfa745 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x36, 0xb5, 0x49, 0xed, 0x58, 0x3d, 0x0c, 0x22, 0xa3, 0x88, 0x48, 0x4e, 0x9e, 0x7a, 0xd0,
	0x93, 0x67, 0x0f, 0x22, 0x78, 0xca, 0x0b, 0x48, 0xda, 0x2e, 0x61, 0xa0, 0xd9, 0x09, 0xbb, 0xa3,
	0x8f, 0xea, 0xf3, 0xb8, 0x9d, 0x4d, 0x50, 0xe8, 0x69, 0xe7, 0xfb, 0x99, 0x9d, 0x8f, 0x0f, 0x56,
	0x7b, 0xe9, 0x78, 0xdb, 0xae, 0x87, 0x20, 0x2a, 0x58, 0xda, 0x53, 0xff, 0x14, 0x80, 0x8d, 0xeb,
	0x38, 0x6a, 0x90, 0xcf, 0x83, 0x21, 0x6a, 0xf2, 0xe0, 0x1d, 0x2c, 0x95, 0x7b, 0x17, 0xb5, 0xed,
	0x07, 0x2a, 0x1e, 0x8a, 0xc7, 0x65, 0xf3, 0x47, 0xe0, 0x25, 0xcc, 0x78, 0x47, 0xb3, 0x44, 0x97,
	0x4d, 0x9a, 0x10, 0x61, 0xae, 0x3c, 0x08, 0x9d, 0x9a, 0xd1, 0x66, 0xbc, 0x86, 0xca, 0x4b, 0xbf,
	0x09, 0x8e, 0xe6, 0xc6, 0x8e, 0x08, 0xaf, 0xa0, 0xfc, 0x6e, 0xf7, 0x12, 0xa8, 0xb4, 0xf5, 0x0c,
	0x0e, 0x6e, 0x09, 0xdc, 0x39, 0x4f, 0x55, 0x76, 0x67, 0x84, 0x04, 0x8b, 0x5d, 0x3a, 0xca, 0x5e,
	0x68, 0x61, 0xc2, 0x04, 0xf1, 0x1e, 0x20, 0xba, 0xee, 0x2b, 0x65, 0xf2, 0x2a, 0x74, 0x66, 0x9f,
	0xfd, 0x63, 0x6a, 0x82, 0xea, 0xb5, 0xed, 0x59, 0xfc, 0x98, 0xb6, 0x98, 0xd2, 0x3e, 0xbd, 0xc3,
	0x6a, 0x6b, 0xca, 0x87, 0xf5, 0x81, 0x2f, 0x70, 0xfe, 0xe6, 0x74, 0x2a, 0x01, 0x2f, 0x72, 0x41,
	0xeb, 0xbc, 0x7d, 0x7b, 0x33, 0xc2, 0xe3, 0x92, 0xea, 0x93, 0x4d, 0x65, 0xda, 0xf3, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x99, 0x5d, 0x07, 0x20, 0x5b, 0x01, 0x00, 0x00,
}
