// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: comms.proto

package comms

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request_CrearOrdenPyme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto    string `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda      string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino     string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Prioritario int32  `protobuf:"varint,6,opt,name=prioritario,proto3" json:"prioritario,omitempty"`
}

func (x *Request_CrearOrdenPyme) Reset() {
	*x = Request_CrearOrdenPyme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_CrearOrdenPyme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_CrearOrdenPyme) ProtoMessage() {}

func (x *Request_CrearOrdenPyme) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_CrearOrdenPyme.ProtoReflect.Descriptor instead.
func (*Request_CrearOrdenPyme) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{0}
}

func (x *Request_CrearOrdenPyme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request_CrearOrdenPyme) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Request_CrearOrdenPyme) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Request_CrearOrdenPyme) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Request_CrearOrdenPyme) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Request_CrearOrdenPyme) GetPrioritario() int32 {
	if x != nil {
		return x.Prioritario
	}
	return 0
}

type Request_CrearOrdenRetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto string `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor    int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda   string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino  string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Request_CrearOrdenRetail) Reset() {
	*x = Request_CrearOrdenRetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_CrearOrdenRetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_CrearOrdenRetail) ProtoMessage() {}

func (x *Request_CrearOrdenRetail) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_CrearOrdenRetail.ProtoReflect.Descriptor instead.
func (*Request_CrearOrdenRetail) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{1}
}

func (x *Request_CrearOrdenRetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request_CrearOrdenRetail) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Request_CrearOrdenRetail) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Request_CrearOrdenRetail) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Request_CrearOrdenRetail) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type Response_CrearOrden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento int32 `protobuf:"varint,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *Response_CrearOrden) Reset() {
	*x = Response_CrearOrden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_CrearOrden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_CrearOrden) ProtoMessage() {}

func (x *Response_CrearOrden) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_CrearOrden.ProtoReflect.Descriptor instead.
func (*Response_CrearOrden) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{2}
}

func (x *Response_CrearOrden) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

type Request_Seguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento int32 `protobuf:"varint,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *Request_Seguimiento) Reset() {
	*x = Request_Seguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_Seguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Seguimiento) ProtoMessage() {}

func (x *Request_Seguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Seguimiento.ProtoReflect.Descriptor instead.
func (*Request_Seguimiento) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{3}
}

func (x *Request_Seguimiento) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

type Response_Seguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Response_Seguimiento) Reset() {
	*x = Response_Seguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Seguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Seguimiento) ProtoMessage() {}

func (x *Response_Seguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Seguimiento.ProtoReflect.Descriptor instead.
func (*Response_Seguimiento) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{4}
}

func (x *Response_Seguimiento) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Request_SolicitarPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
}

func (x *Request_SolicitarPaquete) Reset() {
	*x = Request_SolicitarPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_SolicitarPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_SolicitarPaquete) ProtoMessage() {}

func (x *Request_SolicitarPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_SolicitarPaquete.ProtoReflect.Descriptor instead.
func (*Request_SolicitarPaquete) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{5}
}

func (x *Request_SolicitarPaquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type Response_SolicitarPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo    string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor   int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda  string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Response_SolicitarPaquete) Reset() {
	*x = Response_SolicitarPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_SolicitarPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_SolicitarPaquete) ProtoMessage() {}

func (x *Response_SolicitarPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_SolicitarPaquete.ProtoReflect.Descriptor instead.
func (*Response_SolicitarPaquete) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{6}
}

func (x *Response_SolicitarPaquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response_SolicitarPaquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Response_SolicitarPaquete) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Response_SolicitarPaquete) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Response_SolicitarPaquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type Request_Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Intentos int32  `protobuf:"varint,2,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Fecha    string `protobuf:"bytes,3,opt,name=fecha,proto3" json:"fecha,omitempty"`
	Estado   string `protobuf:"bytes,4,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Request_Estado) Reset() {
	*x = Request_Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request_Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Estado) ProtoMessage() {}

func (x *Request_Estado) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Estado.ProtoReflect.Descriptor instead.
func (*Request_Estado) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{7}
}

func (x *Request_Estado) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request_Estado) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *Request_Estado) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *Request_Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Response_Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recibido string `protobuf:"bytes,1,opt,name=recibido,proto3" json:"recibido,omitempty"`
}

func (x *Response_Estado) Reset() {
	*x = Response_Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Estado) ProtoMessage() {}

func (x *Response_Estado) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Estado.ProtoReflect.Descriptor instead.
func (*Response_Estado) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{8}
}

func (x *Response_Estado) GetRecibido() string {
	if x != nil {
		return x.Recibido
	}
	return ""
}

var File_comms_proto protoreflect.FileDescriptor

var file_comms_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x6d, 0x6d, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x43, 0x72, 0x65, 0x61, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x50, 0x79, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x72,
	0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69,
	0x74, 0x61, 0x72, 0x69, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0x37, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22,
	0x37, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x53, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x2e, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x50, 0x61, 0x71,
	0x75, 0x65, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x50,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x6f, 0x22, 0x6a, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x45, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x65, 0x63, 0x68, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x66, 0x65, 0x63, 0x68, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x2d,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x32, 0x8f, 0x03,
	0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x6d, 0x73, 0x12, 0x4d, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x72,
	0x4f, 0x72, 0x64, 0x65, 0x6e, 0x50, 0x79, 0x6d, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x6e, 0x50, 0x79, 0x6d, 0x65, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x72,
	0x4f, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0x1a, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x43, 0x72, 0x65,
	0x61, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69,
	0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61,
	0x72, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x61, 0x72, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0e,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x15,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x45,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comms_proto_rawDescOnce sync.Once
	file_comms_proto_rawDescData = file_comms_proto_rawDesc
)

func file_comms_proto_rawDescGZIP() []byte {
	file_comms_proto_rawDescOnce.Do(func() {
		file_comms_proto_rawDescData = protoimpl.X.CompressGZIP(file_comms_proto_rawDescData)
	})
	return file_comms_proto_rawDescData
}

var file_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comms_proto_goTypes = []interface{}{
	(*Request_CrearOrdenPyme)(nil),    // 0: comms.Request_CrearOrdenPyme
	(*Request_CrearOrdenRetail)(nil),  // 1: comms.Request_CrearOrdenRetail
	(*Response_CrearOrden)(nil),       // 2: comms.Response_CrearOrden
	(*Request_Seguimiento)(nil),       // 3: comms.Request_Seguimiento
	(*Response_Seguimiento)(nil),      // 4: comms.Response_Seguimiento
	(*Request_SolicitarPaquete)(nil),  // 5: comms.Request_SolicitarPaquete
	(*Response_SolicitarPaquete)(nil), // 6: comms.Response_SolicitarPaquete
	(*Request_Estado)(nil),            // 7: comms.Request_Estado
	(*Response_Estado)(nil),           // 8: comms.Response_Estado
}
var file_comms_proto_depIdxs = []int32{
	0, // 0: comms.Comms.CrearOrdenPyme:input_type -> comms.Request_CrearOrdenPyme
	1, // 1: comms.Comms.CrearOrdenRetail:input_type -> comms.Request_CrearOrdenRetail
	3, // 2: comms.Comms.Seguimiento:input_type -> comms.Request_Seguimiento
	5, // 3: comms.Comms.SolicitarPaquete:input_type -> comms.Request_SolicitarPaquete
	7, // 4: comms.Comms.InformarEstado:input_type -> comms.Request_Estado
	2, // 5: comms.Comms.CrearOrdenPyme:output_type -> comms.Response_CrearOrden
	2, // 6: comms.Comms.CrearOrdenRetail:output_type -> comms.Response_CrearOrden
	4, // 7: comms.Comms.Seguimiento:output_type -> comms.Response_Seguimiento
	6, // 8: comms.Comms.SolicitarPaquete:output_type -> comms.Response_SolicitarPaquete
	8, // 9: comms.Comms.InformarEstado:output_type -> comms.Response_Estado
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comms_proto_init() }
func file_comms_proto_init() {
	if File_comms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_CrearOrdenPyme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_CrearOrdenRetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_CrearOrden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_Seguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Seguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_SolicitarPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_SolicitarPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request_Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comms_proto_goTypes,
		DependencyIndexes: file_comms_proto_depIdxs,
		MessageInfos:      file_comms_proto_msgTypes,
	}.Build()
	File_comms_proto = out.File
	file_comms_proto_rawDesc = nil
	file_comms_proto_goTypes = nil
	file_comms_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommsClient interface {
	CrearOrdenPyme(ctx context.Context, in *Request_CrearOrdenPyme, opts ...grpc.CallOption) (*Response_CrearOrden, error)
	CrearOrdenRetail(ctx context.Context, in *Request_CrearOrdenRetail, opts ...grpc.CallOption) (*Response_CrearOrden, error)
	Seguimiento(ctx context.Context, in *Request_Seguimiento, opts ...grpc.CallOption) (*Response_Seguimiento, error)
	SolicitarPaquete(ctx context.Context, in *Request_SolicitarPaquete, opts ...grpc.CallOption) (*Response_SolicitarPaquete, error)
	InformarEstado(ctx context.Context, in *Request_Estado, opts ...grpc.CallOption) (*Response_Estado, error)
}

type commsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommsClient(cc grpc.ClientConnInterface) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) CrearOrdenPyme(ctx context.Context, in *Request_CrearOrdenPyme, opts ...grpc.CallOption) (*Response_CrearOrden, error) {
	out := new(Response_CrearOrden)
	err := c.cc.Invoke(ctx, "/comms.Comms/CrearOrdenPyme", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) CrearOrdenRetail(ctx context.Context, in *Request_CrearOrdenRetail, opts ...grpc.CallOption) (*Response_CrearOrden, error) {
	out := new(Response_CrearOrden)
	err := c.cc.Invoke(ctx, "/comms.Comms/CrearOrdenRetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) Seguimiento(ctx context.Context, in *Request_Seguimiento, opts ...grpc.CallOption) (*Response_Seguimiento, error) {
	out := new(Response_Seguimiento)
	err := c.cc.Invoke(ctx, "/comms.Comms/Seguimiento", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) SolicitarPaquete(ctx context.Context, in *Request_SolicitarPaquete, opts ...grpc.CallOption) (*Response_SolicitarPaquete, error) {
	out := new(Response_SolicitarPaquete)
	err := c.cc.Invoke(ctx, "/comms.Comms/SolicitarPaquete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) InformarEstado(ctx context.Context, in *Request_Estado, opts ...grpc.CallOption) (*Response_Estado, error) {
	out := new(Response_Estado)
	err := c.cc.Invoke(ctx, "/comms.Comms/InformarEstado", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommsServer is the server API for Comms service.
type CommsServer interface {
	CrearOrdenPyme(context.Context, *Request_CrearOrdenPyme) (*Response_CrearOrden, error)
	CrearOrdenRetail(context.Context, *Request_CrearOrdenRetail) (*Response_CrearOrden, error)
	Seguimiento(context.Context, *Request_Seguimiento) (*Response_Seguimiento, error)
	SolicitarPaquete(context.Context, *Request_SolicitarPaquete) (*Response_SolicitarPaquete, error)
	InformarEstado(context.Context, *Request_Estado) (*Response_Estado, error)
}

// UnimplementedCommsServer can be embedded to have forward compatible implementations.
type UnimplementedCommsServer struct {
}

func (*UnimplementedCommsServer) CrearOrdenPyme(context.Context, *Request_CrearOrdenPyme) (*Response_CrearOrden, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrearOrdenPyme not implemented")
}
func (*UnimplementedCommsServer) CrearOrdenRetail(context.Context, *Request_CrearOrdenRetail) (*Response_CrearOrden, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrearOrdenRetail not implemented")
}
func (*UnimplementedCommsServer) Seguimiento(context.Context, *Request_Seguimiento) (*Response_Seguimiento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seguimiento not implemented")
}
func (*UnimplementedCommsServer) SolicitarPaquete(context.Context, *Request_SolicitarPaquete) (*Response_SolicitarPaquete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarPaquete not implemented")
}
func (*UnimplementedCommsServer) InformarEstado(context.Context, *Request_Estado) (*Response_Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarEstado not implemented")
}

func RegisterCommsServer(s *grpc.Server, srv CommsServer) {
	s.RegisterService(&_Comms_serviceDesc, srv)
}

func _Comms_CrearOrdenPyme_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_CrearOrdenPyme)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).CrearOrdenPyme(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/CrearOrdenPyme",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).CrearOrdenPyme(ctx, req.(*Request_CrearOrdenPyme))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_CrearOrdenRetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_CrearOrdenRetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).CrearOrdenRetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/CrearOrdenRetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).CrearOrdenRetail(ctx, req.(*Request_CrearOrdenRetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_Seguimiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_Seguimiento)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).Seguimiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/Seguimiento",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).Seguimiento(ctx, req.(*Request_Seguimiento))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_SolicitarPaquete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_SolicitarPaquete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).SolicitarPaquete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/SolicitarPaquete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).SolicitarPaquete(ctx, req.(*Request_SolicitarPaquete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_InformarEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_Estado)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).InformarEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/InformarEstado",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).InformarEstado(ctx, req.(*Request_Estado))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comms.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearOrdenPyme",
			Handler:    _Comms_CrearOrdenPyme_Handler,
		},
		{
			MethodName: "CrearOrdenRetail",
			Handler:    _Comms_CrearOrdenRetail_Handler,
		},
		{
			MethodName: "Seguimiento",
			Handler:    _Comms_Seguimiento_Handler,
		},
		{
			MethodName: "SolicitarPaquete",
			Handler:    _Comms_SolicitarPaquete_Handler,
		},
		{
			MethodName: "InformarEstado",
			Handler:    _Comms_InformarEstado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}
